FROM infuseai/dev-container-base-image:latest

# Install your dependencies here
# Please make sure to install the required python dependencies
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt