version: 2

models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders and payments, including both gross and profit-based customer lifetime value metrics

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        description: Total value of a customer's orders including coupon amounts

      - name: net_customer_lifetime_value
        description: Total value of a customer's orders excluding coupon amounts

      - name: total_order_amount
        description: Total value (AUD) of a customer's orders

  - name: customer_segments
    description: This table categorizes customers based on their ordering behavior and value to the company, using derived metrics from their order history and payment information.

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer.
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
    
      - name: number_of_orders
        description: Count of the number of orders a customer has placed.
        tests:
          - not_null
    
      - name: customer_lifetime_value
        description: Total value of all orders including coupon amounts.
    
      - name: net_customer_lifetime_value
        description: Total value of all orders excluding coupon amounts.
    
      - name: order_frequency_segment
        description: Categorization of customers based on how frequently they place orders.
        tests:
          - not_null
          - accepted_values:
              values: ['Frequent Buyer', 'Occasional Buyer', 'Rare Buyer']
    
      - name: value_segment
        description: Categorization of customers based on the gross monetary value they bring to the company.
        tests:
          - accepted_values:
              values: ['High Value', 'Medium Value', 'Low Value']
    
      - name: net_value_segment
        description: Categorization of customers based on the profit-based monetary value they bring to the company.
        tests:
          - accepted_values:
              values: ['High Value', 'Medium Value', 'Low Value']

  - name: customer_order_pattern
    description: This table provides detailed insights into the ordering patterns of customers, including the frequency and recency of their orders.
    
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer.
        tests:
          - unique
          - not_null
    
      - name: first_order
        description: Date (UTC) of a customer's first order.
    
      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order.
    
      - name: number_of_orders
        description: Count of the number of orders a customer has placed.
    
      - name: days_active
        description: The total number of days between a customer's first and most recent orders.
    
      - name: avg_days_between_orders
        description: Average number of days between consecutive orders for a customer.

  - name: orders
    description: This table has basic information about orders, as well as some derived facts based on payments

    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - not_null

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card
        tests:
          - not_null

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon
        tests:
          - not_null

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer
        tests:
          - not_null

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
        tests:
          - not_null

  - name: finance_revenue
    description: This table provides financial metrics for each order, including both gross revenue (including coupons) and profit-based revenue (excluding coupons).

    columns:
      - name: order_id
        description: This is a unique identifier for an order
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed
        tests:
          - not_null

      - name: status
        description: Current status of the order
        tests:
          - not_null
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

      - name: gross_revenue
        description: Total revenue including coupon amounts
        tests:
          - not_null

      - name: net_revenue
        description: Total revenue excluding coupon amounts
        tests:
          - not_null
